name: Docker
on:
  pull_request:
  merge_group:

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build-docker-image:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build the content-generation-service image
        uses: docker/build-push-action@v4
        with:
          push: false
          file: ./Dockerfile
          tags: content-generation-service:PR-${{ env.PR_NUMBER }}
