name: Docker
on:
  pull_request:
  merge_group:

env:
  PR_NUMBER: ${{ github.event.number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cp .env.sample .env
      - name: Start the content-generation-service
        run: docker-compose up -d
      - name: Test for Python in the content-generation-service container
        run: docker exec content-generation-service python -V
