name: Docker
on:
  push:
    branches:
      - main

jobs:
  update-version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - id: version
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          tag-template: '{VERSION}'
          version-command: |
            cat VERSION

  release:
    runs-on: ubuntu-latest
    needs: update-version
    if: ${{ needs.update-version.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_KEY_CONTAINER_REGISTRY }}'
      - uses: google-github-actions/setup-gcloud@v1
      - run: gcloud auth configure-docker
      - uses: docker/build-push-action@v4
        with:
          push: true
          file: ./Dockerfile
          tags: eu.gcr.io/serlo-shared/content-generation-service:${{ needs.update-version.outputs.tag }}
      - name: Test for python in the content-generation-service
        run:
          docker run -it --rm eu.gcr.io/serlo-shared/content-generation-service:${{ needs.update-version.outputs.tag }} python -V
